name: workflow events
on:
    push:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:
    pull_request:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                  echo "Event name: ${{ github.event_name }}"
                  echo "Event name: $GITHUB_EVENT_NAME"
