name: 04-Using Actions
on: workflow_dispatch
env:
    dir: 04-using-action/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install Dependencies
              run: |
                  cd ${{ env.dir }}
                  npm ci
            - name: Run Unit Tests
              run: |
                  cd ${{ env.dir }}
                  npm run test
            - name: npm build
              run: |
                  cd ${{ env.dir }}
                  npm run build
