name: Node.js CI

on: [push]

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Greeting
              uses: ./.github/workflows/reusable.yml
            #   with:
            #       test-input-variable: "Aashish"
