name: working directory
on: [push]
jobs:
    display:
        runs-on: ubuntu-latest
        steps:
            - name: displaying
              run: |
                  pwd
                  ls -a
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_WORKSPACE
